import { FilterConfig, FilterType } from "./filter.models";
import mock from "./mock";

const filter_config: FilterConfig = {
  sync: true,
  defaultValue: "",
  filters: [
    {
      autostart: true,
      required: true,
      label: "Ano Letivo",
      key: "hashAnoLetivo",
      disabledLabel: "Erro",
      placeholder: "Selecione o ano letivo",
      type: FilterType.AnoLetivo,
      update_list: [],
      filter_watch: [],
      reset_time: 24,
      data: mock.anoLetivo,
    },
    {
      required: false,
      label: "Rede",
      key: "hashRede",
      disabledLabel: "Selecione primeiro ano letivo",
      placeholder: "Selecione o ano letivo",
      type: FilterType.Rede,
      update_list: [],
      filter_watch: [FilterType.AnoLetivo, FilterType.Agrupamento],
      reset_time: 24,
      data: mock.rede,
    },
    {
      required: false,
      label: "Escola",
      key: "hashEscola",
      disabledLabel: "Selecione primeiro a rede",
      placeholder: "Selecione",
      type: FilterType.Escola,
      update_list: [],
      filter_watch: [],
      reset_time: 24,
      data: mock.escola,
    },
    {
      required: false,
      label: "Agrupamento",
      key: "hashAgrupamento",
      disabledLabel: "Erro",
      placeholder: "Selecione",
      type: FilterType.Agrupamento,
      update_list: [],
      filter_watch: [FilterType.AnoLetivo],
      reset_time: 24,
      data: mock.agrupamento,
    },
    {
      required: false,
      label: "Turma",
      key: "hashTurma",
      disabledLabel: "Selecione primeiro a rede",
      placeholder: "Selecione",
      type: FilterType.Turma,
      update_list: [],
      filter_watch: [FilterType.AnoLetivo],
      reset_time: 24,
      data: mock.turma,
    },
    {
      required: false,
      label: "Tipo de Avaliacao",
      key: "hashTipoAvaliacao",
      disabledLabel: "Selecione primeiro a rede",
      placeholder: "Selecione",
      type: FilterType.TipoAvaliacao,
      update_list: [],
      filter_watch: [FilterType.AnoLetivo],
      reset_time: 24,
      data: mock.tipoAvaliacao,
    },
    {
      required: false,
      label: "Disciplina",
      key: "hashDisciplina",
      disabledLabel: "Selecione primeiro a rede",
      placeholder: "Selecione",
      type: FilterType.Disciplina,
      update_list: [],
      filter_watch: [FilterType.AnoLetivo],
      reset_time: 24,
      data: mock.disciplina,
    },
    {
      required: false,
      label: "Chamada",
      key: "hashChamada",
      disabledLabel: "",
      placeholder: "Selecione",
      type: FilterType.Chamada,
      update_list: [],
      filter_watch: [],
      reset_time: 24,
      data: mock.chamada,
    },
  ]
}


export default filter_config;
